apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-bundle-overriding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-bundle-overriding
    app.kubernetes.io/part-of: test-app-rgoc
  name: build-suite-test-bundle-overriding
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: build-suite-test-bundle-overriding
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: build-suite-test-bundle-overriding
    spec:
      containers:
      - image: hello-world:latest
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
